name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_16.4.app/Contents/Developer
  # for testing - Removed, as this is no longer a python 2.7 on new systems
  # I need to update esctest to 3.0
  #PYTHON_BIN: /usr/local/bin/python

jobs:
  build:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4

    - name: Checkout esctest for testing
      uses: actions/checkout@v4
      with:
        repository: migueldeicaza/esctest
        path: esctest

    - name: List all files, because this is driving me insane, this does not repro anywhere but github
      run: ls -lR

    - name: Xcode Mac Build
      run: xcodebuild -project TerminalApp/MacTerminal.xcodeproj -scheme MacTerminal

    - name: Xcode iOS Build
      run: |
        xcodebuild -project TerminalApp/iOSTerminal.xcodeproj -scheme iOSTerminal -destination 'generic/platform=iOS' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    - name: Swift Package Build
      run: swift build -v

    - name: Run tests
      run: swift test -v

    - name: Coverage
      run: |
        swift test --enable-code-coverage
        BINDIR=`swift build --show-bin-path`
        TESTDIR=`find $BINDIR -name '*.xctest'`
        xcrun llvm-cov report $TESTDIR/Contents/MacOS/SwiftTermPackageTests --instr-profile=.build/debug/codecov/default.profdata -use-color
