name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_16.4.app/Contents/Developer

jobs:
  build:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4

    - name: Checkout esctest for testing
      uses: actions/checkout@v4
      with:
        repository: migueldeicaza/esctest
        ref: python3
        path: esctest

    - name: List all files, because this is driving me insane, this does not repro anywhere but github
      run: ls -lR

    - name: Xcode Mac Build
      run: xcodebuild -project TerminalApp/MacTerminal.xcodeproj -scheme MacTerminal

    - name: Xcode iOS Build
      run: |
        xcodebuild -project TerminalApp/iOSTerminal.xcodeproj -scheme iOSTerminal -destination 'generic/platform=iOS' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    - name: Swift Package Build
      run: swift build -v

    - name: Run tests
      run: swift test -v

    - name: Coverage
      run: |
        swift test --enable-code-coverage
        BINDIR=$(swift build --show-bin-path)
        xcrun llvm-cov report "$BINDIR/SwiftTermPackageTests.xctest/Contents/MacOS/SwiftTermPackageTests" --instr-profile=.build/debug/codecov/default.profdata -use-color
